# Generated by Django 2.0.5 on 2019-02-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moudle',
            new_name='Module',
        ),
    ]
